---

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  DEBIAN_FRONTEND: noninteractive
  AWS_REGION: eu-west-1

stages:
  - test
  - build
  - test-runtime
  - release
  - post-release

test:compiler:linux:
  image: registry.gitlab.com/inko-lang/development-docker-images:alpine
  stage: test
  before_script:
    - cd compiler
    - ruby --version
    - gem --version
    - bundle --version
    - bundle install --path vendor --retry=3
  script:
    - make test
  cache:
    paths:
      - compiler/vendor/ruby

test:compiler:macos:
  stage: test
  tags:
    - macos
  before_script:
    - cd compiler
    - ruby --version
    - gem --version
    - bundle --version
    - bundle install --path vendor --retry=3
  script:
    - gmake test
  cache:
    key: macos
    paths:
      - compiler/vendor/ruby

test:ivm-nightly:linux:
  image: registry.gitlab.com/inko-lang/development-docker-images:rust-nightly
  stage: test
  before_script:
    - cd vm
    - rustc --version
    - cargo --version
  script:
    - make test
  cache:
    paths:
      - .cargo
      - vm/target

test:ivm-stable:linux:
  image: registry.gitlab.com/inko-lang/development-docker-images:alpine
  stage: test
  before_script:
    - cd vm
    - rustc --version
    - cargo --version
  script:
    - make test
  cache:
    paths:
      - .cargo
      - vm/target

test:ivm-nightly:macos:
  stage: test
  tags:
    - macos
  before_script:
    - cd vm
    - rustc --version
    - cargo --version
  script:
    - rustup run nightly gmake test
  cache:
    key: macos
    paths:
      - .cargo
      - vm/target

test:ivm-stable:macos:
  stage: test
  tags:
    - macos
  before_script:
    - cd vm
    - rustc --version
    - cargo --version
  script:
    - gmake test
  cache:
    key: macos
    paths:
      - .cargo
      - vm/target

lint:clippy:
  image: registry.gitlab.com/inko-lang/development-docker-images:rust-stable
  stage: test
  before_script:
    - cd vm
    - rustc --version
    - cargo --version
  script:
    - make clippy
  cache:
    paths:
      - .cargo
      - vm/target

lint:rustfmt:
  image: registry.gitlab.com/inko-lang/development-docker-images:rust-nightly
  stage: test
  before_script:
    - cd vm
    - rustc --version
    - cargo --version
    - rustfmt --version
  script:
    - make rustfmt-check

lint:versions:
  image: registry.gitlab.com/inko-lang/development-docker-images:alpine
  stage: test
  script:
    - bash scripts/versions.sh

build:ivm:linux:
  image: registry.gitlab.com/inko-lang/development-docker-images:alpine
  stage: build
  before_script:
    - cd vm
    - rustc --version
    - cargo --version
  script:
    - make release
    - mv target/release/ivm ../ivm
    - strip ../ivm
  cache:
    paths:
      - .cargo
      - vm/target
  artifacts:
    expire_in: 1 hour
    paths:
      - ivm

build:ivm:macos:
  stage: build
  tags:
    - macos
  before_script:
    - cd vm
    - rustc --version
    - cargo --version
  script:
    - gmake release
    - mv target/release/ivm ../ivm
    - strip ../ivm
  cache:
    key: macos
    paths:
      - .cargo
      - vm/target
  artifacts:
    expire_in: 1 hour
    paths:
      - ivm

test:runtime:linux:
  image: registry.gitlab.com/inko-lang/development-docker-images:alpine
  stage: test-runtime
  before_script:
    - ruby --version
    - ./ivm --version
    - ./ivm --features
  script:
    - env RUBYLIB=./compiler/lib ./compiler/bin/inko-test -d runtime --vm ./ivm
  dependencies:
    - build:ivm:linux

test:runtime:macos:
  stage: test-runtime
  tags:
    - macos
  before_script:
    - ruby --version
    - ./ivm --version
    - ./ivm --features
  script:
    - env RUBYLIB=./compiler/lib ./compiler/bin/inko-test -d runtime --vm ./ivm
  dependencies:
    - build:ivm:macos

release:source:
  image: registry.gitlab.com/inko-lang/development-docker-images:alpine
  stage: release
  script:
    - make release-source
  only:
    - tags

release:compiled:linux-gnu:
  image: registry.gitlab.com/inko-lang/development-docker-images:rust-stable
  stage: release
  before_script:
    - ruby --version
    - rustc --version
    - cargo --version
    - aws --version
  script:
    - make release-compiled
  only:
    - tags
  cache:
    paths:
      - .cargo
      - vm/target

release:compiled:macos:
  stage: release
  tags:
    - macos
  before_script:
    - ruby --version
    - rustc --version
    - cargo --version
    - aws --version
  script:
    - gmake release-compiled SHA256SUM=gsha256sum
  only:
    - tags
  cache:
    key: macos
    paths:
      - .cargo
      - vm/target

post-release:manifest:
  image: registry.gitlab.com/inko-lang/development-docker-images:alpine
  stage: post-release
  script:
    - make rebuild-manifest
  only:
    - tags
