---

inkoc:
  image: ruby:2.4-alpine
  before_script:
    - cd compiler
    - apk add --update build-base
    - gem install bundler --no-ri --no-rdoc
    - ruby --version
    - gem --version
    - bundle --version
    - bundle install --path vendor --retry=3
  script:
    - bundle exec rake test
  cache:
    paths:
      - vendor/ruby

ivm:
  image: rustlang/rust:nightly
  before_script:
    - cd vm
    - rustc --version
    - cargo --version
  script:
    - cargo test --all --verbose
