---
variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  DEBIAN_FRONTEND: noninteractive
  AWS_REGION: eu-west-1
  # Ensure Windows builds fail when Powershell detects an error.
  ErrorActionPreference: 'STOP'

stages:
  - test
  - test-runtime
  - release
  - post-release

include:
  - local: .gitlab/ci/windows.yml
  - local: .gitlab/ci/macos.yml
  - local: .gitlab/ci/linux.yml
  - local: .gitlab/ci/lints.yml
  - local: .gitlab/ci/releases.yml
