---
image: Visual Studio 2017
build: off
version: '{build}'

platform:
  - x64

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

environment:
  matrix:
    - TARGET: x86_64-pc-windows-gnu
      CHANNEL: nightly
    - TARGET: x86_64-pc-windows-gnu
      CHANNEL: stable

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - set PATH=C:\Users\appveyor\.cargo\bin;%PATH%
  - set PATH=C:\Ruby24-x64\bin;%PATH%
  - set PATH=C:\Python37-x64;%PATH%
  - set PATH=C:\msys64\usr\bin;%PATH%
  # Install dependencies for FFI.
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S automake autoconf texinfo clang"
  # Install the dependencies of the compiler.
  - cd compiler
  - bundle install --path vendor --retry=3
  - cd ..

cache:
  - C:\Users\appveyor\.cargo
  - compiler\vendor

before_test:
  - rustc --version
  - cargo --version
  - ruby --version

test_script:
  - C:\msys64\usr\bin\env MSYSTEM=MINGW64 C:\msys64\usr\bin\bash -l %APPVEYOR_BUILD_FOLDER%\scripts\appveyor.sh
