[package]
name    = "aeon"
version = "0.0.1"
authors = ["Yorick Peterse <yorickpeterse@gmail.com>"]

[lib]
name    = "libaeon"
doctest = false

[[bin]]
name = "aeonvm"
test = false

[dependencies]
getopts = "^0.2"
num_cpus = "^1.0"
rayon = "^0.6"
parking_lot = { version = "^0.3", features = ["nightly"] }
