[package]
name    = "inko"
version = "0.0.1"
authors = ["Yorick Peterse <yorickpeterse@gmail.com>"]

[lib]
name    = "libinko"
doctest = false

[[bin]]
name = "ivm"
test = false

[dependencies]
getopts = "^0.2"
num_cpus = "^1.0"
rayon = "^0.9"
parking_lot = { version = "^0.5", features = ["nightly"] }
fnv = "^1.0"
colored = "^1.6"

[dependencies.rug]
version = "^0.9"
default-features = false
features = ["integer"]

[features]
default = ["system-allocator", "prefetch"]

# Use the system allocator instead of Rust's default (jemalloc)
system-allocator = []

# Enables the use of prefetching to improve performance in various areas. This
# requires a nightly build of Rust.
prefetch = []
