[package]
name = "inko"
version = "0.3.0" # VERSION
authors = ["Yorick Peterse <yorickpeterse@gmail.com>"]

[lib]
name = "libinko"
doctest = false

[[bin]]
name = "ivm"
test = false

[dependencies]
getopts = "^0.2"
num_cpus = "^1.10"
rayon = "^1.0"
parking_lot = "^0.7"
fnv = "^1.0"
time = "^0.1"
num-integer = "^0.1"
float-cmp = "^0.4"
num-bigint = "^0.2"
num-traits = "^0.2"
dirs = "^1.0"
libloading = "^0.5"
libffi = "^0.6"
libffi-sys = ">=0.6.3"
crossbeam-deque = "^0.7"
crossbeam-channel = "^0.3"
