max_width = 80
write_mode = "Overwrite"
use_try_shorthand = true
error_on_line_overflow = false
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
reorder_extern_crates = true
reorder_extern_crates_in_group = true
