---
name: Bug
description: Report a new bug
labels:
  - bug
body:
  - type: textarea
    id: description
    attributes:
      label: Please describe the bug
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating system
      options:
        - Arch Linux
        - Debian
        - Fedora
        - FreeBSD
        - Ubuntu
        - macOS
        - Other
    validations:
      required: true

  - type: input
    id: inko-version
    attributes:
      label: Inko version
    validations:
      required: true
