---
require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4

Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/ClassLength:
  Max: 1000

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/AbcSize:
  Max: 30

Metrics/ParameterLists:
  Max: 10

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 20

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
