[package]
name = "compiler"
version = "0.13.2" # VERSION
authors = ["Yorick Peterse <yorick@yorickpeterse.com>"]
edition = "2021"
license = "MPL-2.0"
build = "build.rs"

[lib]
doctest = false

[dependencies]
unicode-segmentation = "^1.8"
getopts = "^0.2"
ast = { path = "../ast" }
types = { path = "../types" }
fnv = "^1.0"
inkwell = { version = "^0.1", features = ["llvm15-0"] }
llvm-sys-150 = { package = "llvm-sys", version = "150.1.2", features = ["prefer-static"] }
blake2 = "^0.10"

[dev-dependencies]
similar-asserts = "^1.1"
