[package]
name = "compiler"
version.workspace = true
authors = ["Yorick Peterse <yorick@yorickpeterse.com>"]
edition = "2021"
license = "MPL-2.0"
build = "build.rs"
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
ast = { path = "../ast" }
types = { path = "../types" }
location = { path = "../location" }
unicode-segmentation = "^1.10"
getopts = "^0.2"
fnv = "^1.0"
blake3 = "^1.5"
inkwell = { version = "^0.5", features = ["llvm17-0"] }
llvm-sys-170 = { package = "llvm-sys", version = "^170.2", features = ["prefer-static"] }
indexmap = "^2.6"

[dev-dependencies]
similar-asserts = "^1.1"
