[package]
name = "rt"
version = "0.14.0" # VERSION
authors = ["Yorick Peterse <yorick@yorickpeterse.com>"]
edition = "2021"
build = "build.rs"
license = "MPL-2.0"

[lib]
name = "inko"
doctest = false
crate-type = ["staticlib", "lib"]

[dependencies]
crossbeam-utils = "^0.8"
crossbeam-queue = "^0.3"

# We use rustix where possible, but as it doesn't offer support for everything
# (e.g. signal management) we still need to use libc in those cases.
libc = "^0.2"
rand = { version = "^0.8", features = ["default", "small_rng"] }
polling = "^2.8"
unicode-segmentation = "^1.10"
backtrace = "^0.3"
rustix = { version = "^0.38", features = ["fs", "mm", "param", "process", "net", "std", "time"], default-features = false }

[dependencies.socket2]
version = "^0.5"
features = ["all"]
