site_name: The Inko manual
site_description: The Inko programming language manual
site_author: The Inko programming language developers
docs_dir: source
site_dir: build
use_directory_urls: true
repo_url: https://gitlab.com/inko-lang/inko
repo_name: Inko
edit_uri: -/tree/master/docs
theme:
  name: material
  favicon: images/favicon.ico
  logo: images/logo.png
  font: false
  features:
    - navigation.tabs
  palette:
    primary: white
    accent: blue
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - admonition
nav:
  - Home:
    - index.md
    - inko-compared-to-other-languages.md
    - style-guide.md
    - contributing.md
  - Getting started:
    - getting-started/installation.md
    - getting-started/ivm.md
    - getting-started/text-editor-setup.md
    - getting-started/our-first-program.md
    - getting-started/static-typing.md
    - getting-started/basic-types.md
    - getting-started/blocks.md
    - getting-started/objects.md
    - getting-started/traits.md
    - getting-started/modules.md
    - getting-started/variables.md
    - getting-started/operators.md
    - getting-started/control-flow.md
    - getting-started/type-casts.md
    - getting-started/optional-values.md
    - getting-started/generics.md
    - getting-started/error-handling.md
    - getting-started/concurrency.md
    - getting-started/prelude.md
  - Guides:
    - guides/index.md
    - guides/iterators.md
    - guides/sockets.md
  - Virtual machine:
    - virtual-machine/introduction.md
    - virtual-machine/configuration.md
    - virtual-machine/bytecode.md
    - virtual-machine/memory-management.md
    - virtual-machine/scheduling.md
extra:
  social:
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/inko-lang/inko
      name: View on GitLab
    - icon: fontawesome/regular/comment
      link: https://matrix.to/#/+inko:matrix.org
      name: Chat using Matrix
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yorickpeterse
      name: Follow on Twitter
    - icon: fontawesome/brands/reddit
      link: https://reddit.com/r/inko
      name: Join the /r/inko subreddit
