---
name: Build CI container
on:
  workflow_call:
    inputs:
      name:
        description: 'The name of the image to build'
        required: true
        type: string
      runner:
        description: 'The host runner to use'
        required: false
        default: ubuntu-24.04
        type: string
      dockerfile:
        description: 'The directory of the Dockerfile to use'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  NAMESPACE: inko-lang/ci

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ci/docker/${{ inputs.dockerfile }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}:${{ inputs.name }}
