---
name: Build CI container
on:
  workflow_call:
    inputs:
      name:
        description: 'The name of the image to build'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  NAMESPACE: inko-lang/ci

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ci/docker/${{ inputs.name }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}:${{ inputs.name }}
