---
name: Build CI containers
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/container.yml'
      - '.github/workflows/containers.yml'
      - 'ci/docker/*/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read
  packages: write

jobs:
  fedora-amd64:
    uses: ./.github/workflows/container.yml
    with:
      name: fedora-amd64
      dockerfile: fedora
  fedora-arm64:
    uses: ./.github/workflows/container.yml
    with:
      name: fedora-arm64
      dockerfile: fedora
      runner: ubuntu-24.04-arm
  alpine:
    uses: ./.github/workflows/container.yml
    with:
      name: alpine
      dockerfile: alpine
