---
name: CI containers
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'ci/**/*'

permissions:
  contents: read
  packages: write

jobs:
  debian:
    uses: ./.github/workflows/container.yml
    with:
      name: 'debian'
  fedora:
    uses: ./.github/workflows/container.yml
    with:
      name: 'fedora'
  ubuntu:
    uses: ./.github/workflows/container.yml
    with:
      name: 'ubuntu'
  idoc:
    uses: ./.github/workflows/container.yml
    with:
      name: 'idoc'
