---
name: Build CI containers
on:
  workflow_call:

permissions:
  contents: read
  packages: write

jobs:
  debian:
    uses: ./.github/workflows/container.yml
    with:
      name: 'debian'
  fedora:
    uses: ./.github/workflows/container.yml
    with:
      name: 'fedora'
  ubuntu:
    uses: ./.github/workflows/container.yml
    with:
      name: 'ubuntu'
