---
name: CI containers
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'ci/**/*'

jobs:
  arch:
    uses: ./.github/workflows/container.yml
    with:
      name: 'arch'
  debian:
    uses: ./.github/workflows/container.yml
    with:
      name: 'debian'
  fedora:
    uses: ./.github/workflows/container.yml
    with:
      name: 'fedora'
  ubuntu:
    uses: ./.github/workflows/container.yml
    with:
      name: 'ubuntu'
