---
name: Build CI containers
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/container.yml'
      - '.github/workflows/containers.yml'
      - 'ci/docker/*/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read
  packages: write

jobs:
  fedora:
    uses: ./.github/workflows/container.yml
    with:
      name: 'fedora'
  alpine:
    uses: ./.github/workflows/container.yml
    with:
      name: 'alpine'
  debian-amd64:
    uses: ./.github/workflows/container.yml
    with:
      name: 'debian-amd64'
  debian-arm64:
    uses: ./.github/workflows/container.yml
    with:
      name: 'debian-arm64'
