---
name: Build CI containers
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/container.yml'
      - '.github/workflows/containers.yml'
      - 'ci/**/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read
  packages: write

jobs:
  fedora:
    uses: ./.github/workflows/container.yml
    with:
      name: 'fedora'
