---
name: Documentation
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**/*.*'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    if: |
      github.repository == 'inko-lang/inko' && github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            docs/.venv
          key: ${{ runner.os }}-docs-main
      - run: pip install poetry
      - run: poetry config virtualenvs.in-project true
      - run: cd docs && poetry install
      - run: make docs/publish
