---
name: FreeBSD tests
on:
  workflow_call:

env:
  CARGO_HOME: ${{ github.workspace }}/.cargo-home
  LIBRARY_PATH: /usr/local/lib
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

# Due to https://github.com/cross-platform-actions/action/issues/29, jobs should
# use QEMU, instead of xhyve.
jobs:
  amd64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ${{ env.CARGO_HOME }}
            target
          key: freebsd
      - name: Run tests
        uses: cross-platform-actions/action@v0.22.0
        with:
          operating_system: freebsd
          version: '13.2'
          environment_variables: 'CARGO_HOME LIBRARY_PATH CARGO_REGISTRIES_CRATES_IO_PROTOCOL'
          hypervisor: qemu
          image_url: 'https://github.com/inko-lang/freebsd-builder/releases/download/v0.6.6/freebsd-13.2-x86-64.qcow2'
          run: ./ci/freebsd.sh
