---
name: FreeBSD tests
on:
  workflow_call:

env:
  CARGO_HOME: ${{ github.workspace }}/.cargo-home
  RUSTUP_HOME: ${{ github.workspace }}/.rustup-home
  LIBRARY_PATH: /usr/local/lib
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ${{ env.CARGO_HOME }}
            ${{ env.RUSTUP_HOME }}
            target
          key: freebsd
      - name: Run tests
        uses: cross-platform-actions/action@v0.24.0
        with:
          operating_system: freebsd
          version: '14.0'
          memory: 8G
          environment_variables: 'CARGO_HOME RUSTUP_HOME LIBRARY_PATH CARGO_REGISTRIES_CRATES_IO_PROTOCOL'
          image_url: 'https://github.com/inko-lang/freebsd-builder/releases/download/v0.8.0/freebsd-14.0-x86-64.qcow2'
          run: ./ci/freebsd.sh
