---
name: Run linters
on:
  workflow_call:

env:
  # This directory must be named differently from `.cargo`, otherwise it will
  # conflict with our local Cargo configuration.
  CARGO_HOME: ${{ github.workspace }}/.cargo-home

# Lints/checks to always run.
jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: EmbarkStudios/cargo-deny-action@v1

  gitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 10
      - run: pip install gitlint
      - run: git config --global --add safe.directory $PWD
      - run: gitlint --commits "HEAD~9..HEAD"
