---
name: Linux tests
on:
  workflow_call:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        image:
          - arch
          - debian
          - fedora
          - ubuntu
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/inko-lang/ci:${{ matrix.image }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ${{ env.CARGO_HOME }}
            target
          key: ${{ matrix.image }}
      - name: Show version info
        run: rustc --version
      - name: Run compiler tests
        run: cargo test
      - name: Run stdlib tests
        run: 'cd std && cargo run -- test'
