---
name: Linux tests
on:
  workflow_call:

env:
  CARGO_HOME: ${{ github.workspace }}/.cargo-home
  RUSTUP_HOME: ${{ github.workspace }}/.rustup-home
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  amd64:
    name: Linux AMD64
    strategy:
      fail-fast: false
      matrix:
        image:
          - debian
          - fedora
          - ubuntu
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/inko-lang/ci:${{ matrix.image }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ${{ env.CARGO_HOME }}
            ${{ env.RUSTUP_HOME }}
            target
          key: ${{ matrix.image }}
      - name: Show version info
        run: rustc --version
      - name: Run compiler tests
        run: cargo test
      - name: Run stdlib tests
        run: 'cd std && cargo run -- test'
