---
name: macOS tests
on:
  workflow_call:

env:
  CARGO_HOME: ${{ github.workspace }}/.cargo-home
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ${{ env.CARGO_HOME }}
            target
          key: mac
      - name: Install dependencies
        run: ./ci/mac.sh
      - name: Run compiler tests
        run: cargo test
      - name: Run stdlib tests
        run: 'cd std && cargo run -- test'
