---
name: Build

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  lints:
    uses: ./.github/workflows/lint.yml
  linux:
    uses: ./.github/workflows/linux.yml
  mac:
    uses: ./.github/workflows/mac.yml
  freebsd:
    uses: ./.github/workflows/freebsd.yml

  nightly-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs:
      - lints
      - linux
      - mac
      - freebsd
    if: |
      github.repository == 'inko-lang/inko' && github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  docs:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/inko-lang/inko:main
    env:
      AWS_REGION: eu-west-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    needs:
      - nightly-container
    if: |
      github.repository == 'inko-lang/inko' && github.ref_name == 'main'
    steps:
      - name: Install dependencies
        run: microdnf install --quiet --assumeyes rclone awscli2 git tar make
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            docs/build
            ~/.local/share/inko/packages
          key: docs-main
      # This is needed so the paths-filter action doesn't fail with a "dubious
      # path" error.
      - run: git config --global --add safe.directory $PWD
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            docs:
              - 'docs/**'
              - Makefile
      - name: Deploy the documentation
        if: steps.changes.outputs.docs == 'true'
        run: make docs/publish
