---
name: Release
on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  lints:
    uses: ./.github/workflows/lint.yml
  linux:
    uses: ./.github/workflows/linux.yml
  mac:
    uses: ./.github/workflows/mac.yml
  freebsd:
    uses: ./.github/workflows/freebsd.yml

  source:
    runs-on: ubuntu-latest
    needs:
      - lints
      - linux
      - mac
      - freebsd
    env:
      AWS_REGION: eu-west-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v4
      - run: make release/source
      - run: make release/manifest

  container:
    runs-on: ubuntu-latest
    needs:
      - lints
      - linux
      - mac
      - freebsd
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  runtimes:
    runs-on: ubuntu-latest
    needs:
      - lints
      - linux
      - mac
      - freebsd
    env:
      AWS_REGION: eu-west-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Installing dependencies
        run: sudo ./scripts/deps.sh ubuntu:latest
      - name: Installing Rust
        run: ./scripts/rust.sh 1.70
      - name: Generating runtimes
        run: make runtimes

  docs:
    runs-on: ubuntu-latest
    needs:
      - lints
      - linux
      - mac
      - freebsd
    env:
      AWS_REGION: eu-west-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: |
            docs/.venv
          key: ${{ runner.os }}-docs-release
      - run: pip install poetry
      - run: poetry config virtualenvs.in-project true
      - run: cd docs && poetry install
      - run: make docs/publish DOCS_FOLDER=${{ github.ref_name }}
      - run: >
          if [[ ${{ github.ref_name }} = $(git tag -l --sort=-v:refname | head -n1) ]]
            then make docs/publish DOCS_FOLDER=latest
          fi
      - run: make docs/versions
