---
name: Run tests
on:
  workflow_call:

env:
  CARGO_HOME: ${{ github.workspace }}/.cargo-home
  # We set an explicit version to only install the components we need for CI.
  RUSTUP_TOOLCHAIN: '1.78'

jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@reviewdog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          reporter: github-check
          vale_flags: '--no-wrap --sort'

  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v1

  cargo-clippy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/inko-lang/ci:fedora
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: '${{ env.CARGO_HOME }}'
          key: cargo-clippy-${{ hashFiles('Cargo.lock', 'rust-toolchain.toml') }}
      - name: Run clippy
        run: 'cargo clippy -- -D warnings'

  cargo-fmt:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/inko-lang/ci:fedora
    steps:
      - uses: actions/checkout@v4
      - name: Run rustfmt
        run: 'cargo fmt --all --check'

  inko-fmt:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/inko-lang/ci:fedora
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: '${{ env.CARGO_HOME }}'
          key: inko-fmt-${{ hashFiles('Cargo.lock', 'rust-toolchain.toml') }}
      - name: Build the compiler
        run: cargo build
      - name: Check the formatting
        run: 'cd std && cargo run -- fmt --check'

  linux-amd64:
    name: Linux AMD64
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/inko-lang/ci:fedora
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: '${{ env.CARGO_HOME }}'
          key: linux-amd64-${{ hashFiles('Cargo.lock', 'rust-toolchain.toml') }}
      - name: Run compiler tests
        run: cargo test
      - name: Run stdlib tests
        run: 'cd std && cargo run -- test'

  macos-amd64:
    name: macOS AMD64
    runs-on: macos-12
    env:
      RUSTUP_HOME: ${{ github.workspace }}/.rustup-home
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ${{ env.CARGO_HOME }}
            ${{ env.RUSTUP_HOME }}
          key: mac-amd64-${{ hashFiles('Cargo.lock', 'rust-toolchain.toml') }}
      - name: Install dependencies
        run: ./ci/mac.sh
      - name: Run compiler tests
        run: cargo test
      - name: Run stdlib tests
        run: 'cd std && cargo run -- test'

  macos-arm64:
    name: macOS ARM64
    runs-on: macos-14
    env:
      RUSTUP_HOME: ${{ github.workspace }}/.rustup-home
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ${{ env.CARGO_HOME }}
            ${{ env.RUSTUP_HOME }}
          key: mac-arm64-${{ hashFiles('Cargo.lock', 'rust-toolchain.toml') }}
      - name: Install dependencies
        run: ./ci/mac.sh
      - name: Run compiler tests
        run: cargo test
      - name: Run stdlib tests
        run: 'cd std && cargo run -- test'

  freebsd-amd64:
    name: FreeBSD AMD64
    runs-on: ubuntu-latest
    env:
      RUSTUP_HOME: ${{ github.workspace }}/.rustup-home
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ${{ env.CARGO_HOME }}
            ${{ env.RUSTUP_HOME }}
          key: freebsd-${{ hashFiles('Cargo.lock', 'rust-toolchain.toml') }}
      - name: Run tests
        uses: cross-platform-actions/action@v0.24.0
        with:
          operating_system: freebsd
          version: '14.0'
          memory: 8G
          environment_variables: 'CARGO_HOME RUSTUP_HOME'
          image_url: 'https://github.com/inko-lang/freebsd-builder/releases/download/v0.8.0/freebsd-14.0-x86-64.qcow2'
          run: ./ci/freebsd.sh
