---
name: Run tests
on:
  workflow_call:

jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@reviewdog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          reporter: github-check
          vale_flags: '--no-wrap --sort'

  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v1

  cargo-clippy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/inko-lang/ci:fedora
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ${{ env.CARGO_HOME }}
            target
          key: fedora
      - name: Run clippy
        run: 'cargo clippy -- -D warnings'

  cargo-fmt:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/inko-lang/ci:fedora
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ${{ env.CARGO_HOME }}
            target
          key: fedora
      - name: Run rustfmt
        run: 'cargo fmt --all --check'

  inko-fmt:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/inko-lang/ci:fedora
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ${{ env.CARGO_HOME }}
            target
          key: fedora
      - name: Show version info
        run: rustc --version
      - name: Build the compiler
        run: cargo build
      - name: Check the formatting
        run: 'cd std && cargo run -- fmt --check'

  linux:
    uses: ./.github/workflows/linux.yml

  mac:
    uses: ./.github/workflows/mac.yml

  freebsd:
    uses: ./.github/workflows/freebsd.yml
